require(xts)
require(forecast)
projectData<-read.csv("ZonalDemands_2003-2017.csv")
torontoData<-data.frame(Toronto=projectData[,8])
# time_index <- seq(from = as.POSIXct("2003-05-01 00:00",tz="EST"),to = as.POSIXct("2017-12-31 23:00",tz="EST"), by = "hour")
torontoData.ts<-xts(torontoData,order.by = time_index)
plot(torontoData.ts,main="Original Data")
plot(ma(torontoData.ts,order=24),col="red",lwd=1,main="1 Day Moving Average")
plot(ma(torontoData.ts,order=168),col="blue",lwd=1,main="1 Week Moving Average")
plot(ma(torontoData.ts,order=8766),col="orange",lwd=1,main="1 Year Moving Average")
acf(torontoData.ts)
acf2(torontoData.ts)
acf2(diff(torontoData.ts))
acf2(diff(diff(torontoData.ts),24))
acf2(diff(diff(diff(torontoData.ts),24),168))
library(stats)
decompose(torontoData.ts)
stl(torontoData.ts,s.window="periodic")
diffTorontoData<-diff(torontoData.ts)
summary(diffTorontoData)


training<-window(torontoData.ts,end="2015-12-31 23:00:00",tz="EST")
testing<-window(torontoData.ts,start="2016-01-01 00:00:00",tz="EST")
decompose(torontoData.ts)
trainingModel1<-auto.arima(training)
summary(trainingModel1)
testingModel1<-auto.arima(testing)
predictTesting1<-forecast(trainingModel1,h=17544)
accuracy(fitted.values(testingModel1),testing)
accuracy(fitted.values(predictTesting1),testing)
trainingModel2<-ets(training)
summary(trainingModel2)
testingModel2<-ets(testing)
predictTesting2<-forecast(trainingModel2,h=17544)
accuracy(fitted.values(testingModel2),testing)
accuracy(fitted.values(predictTesting2),testing)
#ARIMA model works better than ETS model.
